# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class E2c < Formula
  desc "e2c is AWS EC2 Terminal UI Manager. Inspired by k9s and e1s."
  homepage "https://github.com/nlamirault/e2c"
  version "0.1.0"
  license "Apache v2"

  on_macos do
    url "https://github.com/nlamirault/e2c/releases/download/v0.1.0/e2c_Darwin_all.tar.gz"
    sha256 "150297825c26e9112817b4827127856cb948dcd12d3c8e7f713fdd918be704c2"

    def install
      bin.install "e2c"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nlamirault/e2c/releases/download/v0.1.0/e2c_Linux_x86_64.tar.gz"
      sha256 "5cb56b237a3ecdc5187172c381c8a4935b8b620bf7f4c53c80c9eb2311d5c80d"
      def install
        bin.install "e2c"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nlamirault/e2c/releases/download/v0.1.0/e2c_Linux_arm64.tar.gz"
      sha256 "230d00aa56b495a652e5ef7f0dc96231a5c77e35ca5f1be5c7d3da0d489c4b76"
      def install
        bin.install "e2c"
      end
    end
  end
end
