# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G1c < Formula
  desc "g1c is Google Cloud Instances Terminal UI Manager. Inspired by k9s and e1s."
  homepage "https://github.com/nlamirault/g1c"
  version "0.2.0"
  license "Apache v2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nlamirault/g1c/releases/download/v0.2.0/g1c_darwin_arm64_v0.2.0"
      sha256 "5a2019b08c00f929a00247030dc4e489d852f08199487e5a10bbbcce67f54d26"

      def install
        bin.install "g1c_darwin_arm64_v0.2.0" => "g1c"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nlamirault/g1c/releases/download/v0.2.0/g1c_linux_amd64_v0.2.0"
      sha256 "c858ece948b7abbf7b200e66343fe09dbf1771893503e7f8077f581de1f689eb"
      def install
        bin.install "g1c_linux_amd64_v0.2.0" => "g1c"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nlamirault/g1c/releases/download/v0.2.0/g1c_linux_arm64_v0.2.0"
      sha256 "4dc80d9f35e1bb57147d908eb0b5210115f8ff06d89e2d155de6e22fd28e91e6"
      def install
        bin.install "g1c_linux_arm64_v0.2.0" => "g1c"
      end
    end
  end
end
