# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ltui < Formula
  desc "ltui is Google Cloud Instances Terminal UI Manager. Inspired by k9s and e1s."
  homepage "https://github.com/nlamirault/ltui"
  version "0.1.0"
  license "Apache v2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nlamirault/ltui/releases/download/v0.1.0/ltui_darwin_arm64_v0.1.0"
      sha256 "4729b85eee2df316a9d8f2638b31a849b4218d6344741762d97a63344ed19d1c"

      def install
        bin.install "ltui_darwin_arm64_v0.1.0" => "ltui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nlamirault/ltui/releases/download/v0.1.0/ltui_linux_arm64_v0.1.0"
      sha256 "4f6b712be86718ff2db869ccdb84a7c34e8a55c373002a17cfe7a9437e95594a"
      def install
        bin.install "ltui_linux_arm64_v0.1.0" => "ltui"
      end
    end
  end
end
